### ISSUE TITLE
Why do the results in the files under the path SASRec/src/output not correspond to the original paper?

### ISSUE THREAD

**Issue by anonymouscoder1022** [KingGugu/RepPad#1]
Why do the results in the files under the path SASRec/src/output not correspond to the original paper?

For example: In SASRec/src/output/SASRec-Toys_and_Games-2.txt, the recorded results are: {'Epoch': 0, 'HIT@5': '0.0570', 'NDCG@5': '0.0390', 'HIT@10': '0.0803', 'NDCG@10': '0.0465', 'HIT@20': '0.1107', 'NDCG@20': '0.0542'}

However, the results in the original paper (Table 7) are: 'HIT@10': 0.0843 'HIT@20': 0.1142 'NDCG@10': 0.0476 'NDCG@20': 0.0551

The same issue occurs with other files as well. If I misunderstood something, I would appreciate your clarification.

**Comment by KingGugu** [comment]
Thank you very much for your interest in our work. Since I can't use my computer for the next few days, I just checked the code on my phone. 

In the paper, we usually report the average results after running the code multiple times, but the repository only uploaded the record of one code run. 

In addition, you can try to run the experiment with the parameter aug_type=2, because the record in the file is performed under aug_type=1.

**Comment by KingGugu** [comment]
If you have any new questions, please feel free to open a new issue to ask.
